FROM node:latest

WORKDIR /app
ADD . /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --only=production && npm cache clean --force
RUN npm install react-scripts
CMD ["npm", "run", "start"]